/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Dan
 */
public class CardGallery extends javax.swing.JPanel {

    /**
     * Creates new form CardGallery
     */
    public CardGallery() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardGalleryPnl = new javax.swing.JPanel();
        indexCardPlaceholder = new javax.swing.JLabel();
        flipAnsBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(336, 532));
        setLayout(null);

        cardGalleryPnl.setBackground(new java.awt.Color(174, 168, 211));
        cardGalleryPnl.setMinimumSize(new java.awt.Dimension(336, 532));
        cardGalleryPnl.setLayout(null);

        indexCardPlaceholder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/indexCardExample.png"))); // NOI18N
        indexCardPlaceholder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        cardGalleryPnl.add(indexCardPlaceholder);
        indexCardPlaceholder.setBounds(23, 20, 290, 290);

        flipAnsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flip.png"))); // NOI18N
        flipAnsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flipAnsBtnActionPerformed(evt);
            }
        });
        cardGalleryPnl.add(flipAnsBtn);
        flipAnsBtn.setBounds(18, 345, 300, 50);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrowL.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        cardGalleryPnl.add(jButton1);
        jButton1.setBounds(17, 430, 75, 75);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrowR.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        cardGalleryPnl.add(jButton2);
        jButton2.setBounds(240, 430, 75, 75);

        add(cardGalleryPnl);
        cardGalleryPnl.setBounds(0, 0, 336, 532);
    }// </editor-fold>//GEN-END:initComponents

    private void flipAnsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flipAnsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flipAnsBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardGalleryPnl;
    private javax.swing.JButton flipAnsBtn;
    private javax.swing.JLabel indexCardPlaceholder;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
