/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Dan
 */
public class CreateCard extends javax.swing.JPanel {

    /**
     * Creates new form CreateCard
     */
    public CreateCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        indexCards = new javax.swing.JPanel();
        createCardBtn = new javax.swing.JButton();
        questionTxtLbl = new javax.swing.JLabel();
        questionTxtTF = new javax.swing.JTextField();
        answerOneLbl = new javax.swing.JLabel();
        answerOneTF = new javax.swing.JTextField();
        answerTwoLbl = new javax.swing.JLabel();
        answerTwoTF = new javax.swing.JTextField();
        answerThreeLbl = new javax.swing.JLabel();
        answerThreeTF = new javax.swing.JTextField();
        answerFourLbl = new javax.swing.JLabel();
        answerFourTF = new javax.swing.JTextField();
        tickAnswerLbl = new javax.swing.JLabel();
        ansOneRadio = new javax.swing.JRadioButton();
        ansTwoRadio = new javax.swing.JRadioButton();
        ansThreeRadio = new javax.swing.JRadioButton();
        ansFourRadio = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(336, 532));
        setPreferredSize(new java.awt.Dimension(336, 532));
        setLayout(null);

        indexCards.setBackground(new java.awt.Color(174, 168, 211));
        indexCards.setMaximumSize(new java.awt.Dimension(336, 532));
        indexCards.setMinimumSize(new java.awt.Dimension(336, 532));
        indexCards.setLayout(null);

        createCardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/createCard.png"))); // NOI18N
        createCardBtn.setAlignmentX(100.0F);
        createCardBtn.setAlignmentY(100.0F);
        createCardBtn.setBorder(null);
        createCardBtn.setContentAreaFilled(false);
        createCardBtn.setPreferredSize(new java.awt.Dimension(220, 77));
        createCardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCardBtnActionPerformed(evt);
            }
        });
        indexCards.add(createCardBtn);
        createCardBtn.setBounds(18, 420, 300, 50);

        questionTxtLbl.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        questionTxtLbl.setForeground(new java.awt.Color(255, 255, 255));
        questionTxtLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionTxtLbl.setText("Question Text:");
        indexCards.add(questionTxtLbl);
        questionTxtLbl.setBounds(0, 20, 336, 29);

        questionTxtTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionTxtTFActionPerformed(evt);
            }
        });
        indexCards.add(questionTxtTF);
        questionTxtTF.setBounds(40, 60, 256, 40);

        answerOneLbl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        answerOneLbl.setForeground(new java.awt.Color(255, 255, 255));
        answerOneLbl.setText("Answer One:");
        indexCards.add(answerOneLbl);
        answerOneLbl.setBounds(15, 120, 200, 22);

        answerOneTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerOneTFActionPerformed(evt);
            }
        });
        indexCards.add(answerOneTF);
        answerOneTF.setBounds(145, 115, 150, 30);

        answerTwoLbl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        answerTwoLbl.setForeground(new java.awt.Color(255, 255, 255));
        answerTwoLbl.setText("Answer Two:");
        indexCards.add(answerTwoLbl);
        answerTwoLbl.setBounds(15, 160, 200, 22);

        answerTwoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerTwoTFActionPerformed(evt);
            }
        });
        indexCards.add(answerTwoTF);
        answerTwoTF.setBounds(145, 155, 150, 30);

        answerThreeLbl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        answerThreeLbl.setForeground(new java.awt.Color(255, 255, 255));
        answerThreeLbl.setText("Answer Three:");
        indexCards.add(answerThreeLbl);
        answerThreeLbl.setBounds(15, 200, 200, 22);

        answerThreeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerThreeTFActionPerformed(evt);
            }
        });
        indexCards.add(answerThreeTF);
        answerThreeTF.setBounds(145, 195, 150, 30);

        answerFourLbl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        answerFourLbl.setForeground(new java.awt.Color(255, 255, 255));
        answerFourLbl.setText("Answer Four:");
        indexCards.add(answerFourLbl);
        answerFourLbl.setBounds(15, 240, 200, 22);

        answerFourTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerFourTFActionPerformed(evt);
            }
        });
        indexCards.add(answerFourTF);
        answerFourTF.setBounds(145, 235, 150, 30);

        tickAnswerLbl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tickAnswerLbl.setForeground(new java.awt.Color(255, 255, 255));
        tickAnswerLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tickAnswerLbl.setText("(Select the correct answer)");
        tickAnswerLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        indexCards.add(tickAnswerLbl);
        tickAnswerLbl.setBounds(18, 280, 300, 22);

        ansOneRadio.setContentAreaFilled(false);
        indexCards.add(ansOneRadio);
        ansOneRadio.setBounds(298, 120, 20, 18);

        ansTwoRadio.setContentAreaFilled(false);
        indexCards.add(ansTwoRadio);
        ansTwoRadio.setBounds(298, 160, 20, 18);

        ansThreeRadio.setContentAreaFilled(false);
        indexCards.add(ansThreeRadio);
        ansThreeRadio.setBounds(298, 200, 20, 18);

        ansFourRadio.setContentAreaFilled(false);
        indexCards.add(ansFourRadio);
        ansFourRadio.setBounds(298, 240, 20, 18);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blue", "Red", "Yellow", "Green" }));
        indexCards.add(jComboBox1);
        jComboBox1.setBounds(196, 350, 80, 20);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select colour: ");
        indexCards.add(jLabel1);
        jLabel1.setBounds(60, 350, 200, 22);

        add(indexCards);
        indexCards.setBounds(0, 0, 336, 532);
    }// </editor-fold>//GEN-END:initComponents

    private void createCardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCardBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createCardBtnActionPerformed

    private void questionTxtTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionTxtTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_questionTxtTFActionPerformed

    private void answerOneTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerOneTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerOneTFActionPerformed

    private void answerTwoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerTwoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerTwoTFActionPerformed

    private void answerThreeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerThreeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerThreeTFActionPerformed

    private void answerFourTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerFourTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerFourTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ansFourRadio;
    private javax.swing.JRadioButton ansOneRadio;
    private javax.swing.JRadioButton ansThreeRadio;
    private javax.swing.JRadioButton ansTwoRadio;
    private javax.swing.JLabel answerFourLbl;
    private javax.swing.JTextField answerFourTF;
    private javax.swing.JLabel answerOneLbl;
    private javax.swing.JTextField answerOneTF;
    private javax.swing.JLabel answerThreeLbl;
    private javax.swing.JTextField answerThreeTF;
    private javax.swing.JLabel answerTwoLbl;
    private javax.swing.JTextField answerTwoTF;
    private javax.swing.JButton createCardBtn;
    private javax.swing.JPanel indexCards;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel questionTxtLbl;
    private javax.swing.JTextField questionTxtTF;
    private javax.swing.JLabel tickAnswerLbl;
    // End of variables declaration//GEN-END:variables
}
