/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

/**
 * ImageQuizGUI.java
 * @author Danny O'Sullivan
 * Student No. x14110750
 */
public class ImageQuizGUI extends javax.swing.JPanel {

    /**
     * Creates new form ImageQuizGUI
     */
    public ImageQuizGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageQuizPanel = new javax.swing.JPanel();
        AQTextField = new javax.swing.JTextField();
        BQTextField = new javax.swing.JTextField();
        CQTextField = new javax.swing.JTextField();
        QuestionLbl = new javax.swing.JLabel();
        AQLbl = new javax.swing.JLabel();
        BQLbl = new javax.swing.JLabel();
        CQLbl = new javax.swing.JLabel();
        ImageQLbl = new javax.swing.JLabel();
        NextQBttn = new javax.swing.JButton();

        setLayout(null);

        ImageQuizPanel.setBackground(new java.awt.Color(245, 171, 53));
        ImageQuizPanel.setLayout(null);
        ImageQuizPanel.add(AQTextField);
        AQTextField.setBounds(41, 310, 268, 30);
        ImageQuizPanel.add(BQTextField);
        BQTextField.setBounds(41, 378, 271, 30);

        CQTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CQTextFieldActionPerformed(evt);
            }
        });
        ImageQuizPanel.add(CQTextField);
        CQTextField.setBounds(42, 444, 270, 30);

        QuestionLbl.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        QuestionLbl.setText("Please Label the following areas of the Heart:");
        ImageQuizPanel.add(QuestionLbl);
        QuestionLbl.setBounds(10, 274, 299, 18);

        AQLbl.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        AQLbl.setText("A.");
        ImageQuizPanel.add(AQLbl);
        AQLbl.setBounds(10, 315, 21, 18);

        BQLbl.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        BQLbl.setText("B.");
        ImageQuizPanel.add(BQLbl);
        BQLbl.setBounds(10, 383, 21, 18);

        CQLbl.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        CQLbl.setText("C.");
        ImageQuizPanel.add(CQLbl);
        CQLbl.setBounds(10, 449, 22, 18);

        ImageQLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/heart.jpg"))); // NOI18N
        ImageQuizPanel.add(ImageQLbl);
        ImageQLbl.setBounds(17, 15, 300, 235);

        NextQBttn.setBackground(new java.awt.Color(255, 255, 255));
        NextQBttn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        NextQBttn.setText("Next");
        NextQBttn.setContentAreaFilled(false);
        NextQBttn.setOpaque(true);
        NextQBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextQBttnActionPerformed(evt);
            }
        });
        ImageQuizPanel.add(NextQBttn);
        NextQBttn.setBounds(250, 488, 75, 30);

        add(ImageQuizPanel);
        ImageQuizPanel.setBounds(0, 0, 336, 532);
    }// </editor-fold>//GEN-END:initComponents

    private void CQTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CQTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CQTextFieldActionPerformed

    private void NextQBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextQBttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NextQBttnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AQLbl;
    private javax.swing.JTextField AQTextField;
    private javax.swing.JLabel BQLbl;
    private javax.swing.JTextField BQTextField;
    private javax.swing.JLabel CQLbl;
    private javax.swing.JTextField CQTextField;
    private javax.swing.JLabel ImageQLbl;
    private javax.swing.JPanel ImageQuizPanel;
    private javax.swing.JButton NextQBttn;
    private javax.swing.JLabel QuestionLbl;
    // End of variables declaration//GEN-END:variables
}
