/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.awt.LayoutManager;

/**
 *
 * @author Paul
 */
public class IndexCards extends javax.swing.JPanel {

    /**
     * Creates new form IndexCards
     */
    public IndexCards() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        indexCards = new javax.swing.JPanel();
        cardGalleryBtn = new javax.swing.JButton();
        createCardBtn = new javax.swing.JButton();
        testYourselfBtn = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMinimumSize(new java.awt.Dimension(336, 532));
        setPreferredSize(new java.awt.Dimension(336, 532));
        setLayout(null);

        indexCards.setBackground(new java.awt.Color(174, 168, 211));
        indexCards.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        indexCards.setMaximumSize(new java.awt.Dimension(336, 532));
        indexCards.setMinimumSize(new java.awt.Dimension(336, 532));
        indexCards.setLayout(null);

        cardGalleryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cardGallery.png"))); // NOI18N
        cardGalleryBtn.setAlignmentX(100.0F);
        cardGalleryBtn.setAlignmentY(100.0F);
        cardGalleryBtn.setBorder(null);
        cardGalleryBtn.setContentAreaFilled(false);
        cardGalleryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cardGalleryBtn.setPreferredSize(new java.awt.Dimension(220, 77));
        cardGalleryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardGalleryBtnActionPerformed(evt);
            }
        });
        indexCards.add(cardGalleryBtn);
        cardGalleryBtn.setBounds(18, 130, 300, 50);

        createCardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/createCard.png"))); // NOI18N
        createCardBtn.setAlignmentX(100.0F);
        createCardBtn.setAlignmentY(100.0F);
        createCardBtn.setBorder(null);
        createCardBtn.setContentAreaFilled(false);
        createCardBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createCardBtn.setPreferredSize(new java.awt.Dimension(220, 77));
        createCardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCardBtnActionPerformed(evt);
            }
        });
        indexCards.add(createCardBtn);
        createCardBtn.setBounds(18, 220, 300, 50);

        testYourselfBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/testYourself.png"))); // NOI18N
        testYourselfBtn.setAlignmentX(100.0F);
        testYourselfBtn.setAlignmentY(100.0F);
        testYourselfBtn.setBorder(null);
        testYourselfBtn.setContentAreaFilled(false);
        testYourselfBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        testYourselfBtn.setPreferredSize(new java.awt.Dimension(220, 77));
        testYourselfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testYourselfBtnActionPerformed(evt);
            }
        });
        indexCards.add(testYourselfBtn);
        testYourselfBtn.setBounds(18, 310, 300, 50);

        add(indexCards);
        indexCards.setBounds(0, 0, 336, 532);
    }// </editor-fold>//GEN-END:initComponents

    private void cardGalleryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardGalleryBtnActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "CARD GALLERY");
        }
    }//GEN-LAST:event_cardGalleryBtnActionPerformed

    private void createCardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCardBtnActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "CREATE CARD");
        }
    }//GEN-LAST:event_createCardBtnActionPerformed

    private void testYourselfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testYourselfBtnActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "TEST YOURSELF");
        }
    }//GEN-LAST:event_testYourselfBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cardGalleryBtn;
    private javax.swing.JButton createCardBtn;
    private javax.swing.JPanel indexCards;
    private javax.swing.JButton testYourselfBtn;
    // End of variables declaration//GEN-END:variables
}
