/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import java.awt.CardLayout;
import java.awt.LayoutManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author x14729249
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        headerTitleLbl.setText("Login");
        
        //create ActionListener for checking time
        ActionListener checkTime = new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                setTime();
            }
        };
        new Timer(1000, checkTime).start();    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPnl = new javax.swing.JPanel();
        nameLbl = new javax.swing.JLabel();
        certLbl = new javax.swing.JLabel();
        levelLbl = new javax.swing.JLabel();
        nameTf = new javax.swing.JTextField();
        levelDrpDwn = new javax.swing.JComboBox();
        certDrpDwn = new javax.swing.JComboBox();
        loginBtn = new javax.swing.JButton();
        headerPnl = new javax.swing.JPanel();
        headerTitleLbl = new javax.swing.JLabel();
        currentDayLbl = new javax.swing.JLabel();
        currentTimeLbl = new javax.swing.JLabel();
        currentDateLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(377, 708));
        setMinimumSize(new java.awt.Dimension(377, 708));
        setPreferredSize(new java.awt.Dimension(377, 708));
        setLayout(null);

        LoginPnl.setBackground(new java.awt.Color(52, 73, 94));
        LoginPnl.setToolTipText("");
        LoginPnl.setMaximumSize(new java.awt.Dimension(336, 532));
        LoginPnl.setMinimumSize(new java.awt.Dimension(336, 532));
        LoginPnl.setLayout(null);

        nameLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(127, 140, 141));
        nameLbl.setText("Name:");
        LoginPnl.add(nameLbl);
        nameLbl.setBounds(50, 150, 100, 30);

        certLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        certLbl.setForeground(new java.awt.Color(127, 140, 141));
        certLbl.setText("Certificate:");
        LoginPnl.add(certLbl);
        certLbl.setBounds(50, 250, 100, 30);

        levelLbl.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        levelLbl.setForeground(new java.awt.Color(127, 140, 141));
        levelLbl.setText("Level:");
        LoginPnl.add(levelLbl);
        levelLbl.setBounds(50, 200, 100, 30);

        nameTf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nameTf.setBorder(null);
        LoginPnl.add(nameTf);
        nameTf.setBounds(170, 150, 150, 25);

        levelDrpDwn.setBackground(new java.awt.Color(52, 73, 94));
        levelDrpDwn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        levelDrpDwn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose One", "Higher", "Ordinary", "Foundation" }));
        levelDrpDwn.setBorder(null);
        levelDrpDwn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LoginPnl.add(levelDrpDwn);
        levelDrpDwn.setBounds(170, 200, 150, 25);

        certDrpDwn.setBackground(new java.awt.Color(52, 73, 94));
        certDrpDwn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        certDrpDwn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose One", "Leaving Cert", "Junior Cert" }));
        certDrpDwn.setBorder(null);
        certDrpDwn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LoginPnl.add(certDrpDwn);
        certDrpDwn.setBounds(170, 250, 150, 25);

        loginBtn.setBackground(new java.awt.Color(135, 211, 124));
        loginBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("LOGIN");
        loginBtn.setBorder(null);
        loginBtn.setContentAreaFilled(false);
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.setOpaque(true);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        LoginPnl.add(loginBtn);
        loginBtn.setBounds(120, 320, 100, 25);

        add(LoginPnl);
        LoginPnl.setBounds(20, 90, 336, 532);

        headerPnl.setBackground(new java.awt.Color(52, 73, 94));
        headerPnl.setForeground(new java.awt.Color(127, 140, 141));
        headerPnl.setToolTipText("");
        headerPnl.setLayout(null);

        headerTitleLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        headerTitleLbl.setForeground(new java.awt.Color(127, 140, 141));
        headerTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerPnl.add(headerTitleLbl);
        headerTitleLbl.setBounds(10, 35, 360, 28);

        currentDayLbl.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        currentDayLbl.setForeground(new java.awt.Color(127, 140, 141));
        currentDayLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        headerPnl.add(currentDayLbl);
        currentDayLbl.setBounds(15, 5, 60, 15);

        currentTimeLbl.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        currentTimeLbl.setForeground(new java.awt.Color(127, 140, 141));
        currentTimeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerPnl.add(currentTimeLbl);
        currentTimeLbl.setBounds(95, 5, 185, 15);

        currentDateLbl.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        currentDateLbl.setForeground(new java.awt.Color(127, 140, 141));
        currentDateLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerPnl.add(currentDateLbl);
        currentDateLbl.setBounds(280, 5, 90, 15);

        add(headerPnl);
        headerPnl.setBounds(0, 0, 380, 70);

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents
    
    private void setTime(){
        Date myDate = new Date();
        SimpleDateFormat curDay = new SimpleDateFormat("E");
        SimpleDateFormat curTime = new SimpleDateFormat("HH:mm:ss");
        SimpleDateFormat curDate = new SimpleDateFormat("dd/MM/yyyy");
        currentDayLbl.setText(curDay.format(myDate));
        currentTimeLbl.setText(curTime.format(myDate));
        currentDateLbl.setText(curDate.format(myDate));
    }
    
    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if(layout instanceof CardLayout){
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "MAIN");
        }
    }//GEN-LAST:event_loginBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPnl;
    private javax.swing.JComboBox certDrpDwn;
    private javax.swing.JLabel certLbl;
    private javax.swing.JLabel currentDateLbl;
    private javax.swing.JLabel currentDayLbl;
    private javax.swing.JLabel currentTimeLbl;
    private javax.swing.JPanel headerPnl;
    private javax.swing.JLabel headerTitleLbl;
    private javax.swing.JComboBox levelDrpDwn;
    private javax.swing.JLabel levelLbl;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTf;
    // End of variables declaration//GEN-END:variables
}
