/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.awt.FlowLayout;
import java.awt.LayoutManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author x14729249
 */
public class MainScreenPanel extends javax.swing.JPanel {
    JPanel cardsContainer;
    
    /**
     * Creates new form MainScreenPanel
     */
    public MainScreenPanel() {
        initComponents();
        
        //Creating and instantiating Timetable classes
        Timetable timetableContent = new Timetable();
        TaskInfo myTaskInfo = new TaskInfo();
        
        //Creating and instantiating Quiz classes
        QuizMainGUI myQuizMain = new QuizMainGUI();
        MultiQuizGUI myMultiQuiz = new MultiQuizGUI();
        ImageQuizGUI myImageQuiz = new ImageQuizGUI();
        TextQuizGUI myTextQuiz = new TextQuizGUI();
        
        //Creating and instantiating Index Card classes
        IndexCards myIndexCards = new IndexCards();
        CardGallery myCardGallery = new CardGallery();
        CreateCard myCreateCard = new CreateCard();
        TestYourself myTestYourself = new TestYourself();
        
        //Creating and instantiating Progress Tracker classes
        ProgressGUI progressGUI = new ProgressGUI();
        ProgressAverageGUI averageGUI = new ProgressAverageGUI();
        ProgressSubjectGUI subjectGUI = new ProgressSubjectGUI();
        
        //initialising the cards container
        cardsContainer = new JPanel(new CardLayout());
        
        //adding Timetable classes to the cards container
        cardsContainer.add(timetableContent, "TIMETABLE");
        cardsContainer.add(myTaskInfo, "TASK INFO");
        
        //adding Quiz classes to the cards container
        cardsContainer.add(myQuizMain, "QUIZ");
        cardsContainer.add(myMultiQuiz, "MULTI QUIZ");
        cardsContainer.add(myImageQuiz, "IMAGE QUIZ");
        cardsContainer.add(myTextQuiz, "TEXT QUIZ");
        
        //adding Index Card classes to the cards container
        cardsContainer.add(myIndexCards, "INDEX CARDS");
        cardsContainer.add(myCardGallery, "CARD GALLERY");
        cardsContainer.add(myCreateCard, "CREATE CARD");
        cardsContainer.add(myTestYourself, "TEST YOURSELF");
        
        //adding Progress Tracker Classes to the cards container
        cardsContainer.add(progressGUI, "PROGRESS");
        cardsContainer.add(averageGUI, "AVERAGE");
        cardsContainer.add(subjectGUI, "SUBJECT");
        
        contentPnl.setLayout(new FlowLayout(0, 0, 0));
        contentPnl.add(cardsContainer);
        CardLayout cl = (CardLayout)(cardsContainer.getLayout());
        cl.show(cardsContainer, "TIMETABLE");
        
        timetableBtn.setBackground(new java.awt.Color(135, 211, 124));
        headerTitleLbl.setText("Timetable");
        
        //create ActionListener for checking time
        ActionListener checkTime = new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                setTime();
            }
        };
        new Timer(1000, checkTime).start();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPnl = new javax.swing.JPanel();
        timetableBtn = new javax.swing.JButton();
        quizBtn = new javax.swing.JButton();
        indexCardsBtn = new javax.swing.JButton();
        progressTrackerBtn = new javax.swing.JButton();
        headerPnl = new javax.swing.JPanel();
        headerTitleLbl = new javax.swing.JLabel();
        currentDayLbl = new javax.swing.JLabel();
        currentTimeLbl = new javax.swing.JLabel();
        currentDateLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(377, 708));
        setMinimumSize(new java.awt.Dimension(377, 708));
        setPreferredSize(new java.awt.Dimension(377, 708));
        setLayout(null);

        contentPnl.setMaximumSize(new java.awt.Dimension(336, 532));
        contentPnl.setMinimumSize(new java.awt.Dimension(336, 532));
        contentPnl.setPreferredSize(new java.awt.Dimension(336, 532));
        contentPnl.setLayout(null);
        add(contentPnl);
        contentPnl.setBounds(20, 90, 336, 532);

        timetableBtn.setBackground(new java.awt.Color(38, 166, 91));
        timetableBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        timetableBtn.setForeground(new java.awt.Color(255, 255, 255));
        timetableBtn.setText("Timetable");
        timetableBtn.setContentAreaFilled(false);
        timetableBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timetableBtn.setOpaque(true);
        timetableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timetableBtnActionPerformed(evt);
            }
        });
        add(timetableBtn);
        timetableBtn.setBounds(0, 640, 94, 65);

        quizBtn.setBackground(new java.awt.Color(230, 126, 34));
        quizBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        quizBtn.setForeground(new java.awt.Color(255, 255, 255));
        quizBtn.setText("Quiz");
        quizBtn.setContentAreaFilled(false);
        quizBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quizBtn.setOpaque(true);
        quizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizBtnActionPerformed(evt);
            }
        });
        add(quizBtn);
        quizBtn.setBounds(94, 640, 94, 65);

        indexCardsBtn.setBackground(new java.awt.Color(191, 85, 236));
        indexCardsBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        indexCardsBtn.setForeground(new java.awt.Color(255, 255, 255));
        indexCardsBtn.setText("<html>Index<br>Cards</html>");
        indexCardsBtn.setContentAreaFilled(false);
        indexCardsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        indexCardsBtn.setOpaque(true);
        indexCardsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexCardsBtnActionPerformed(evt);
            }
        });
        add(indexCardsBtn);
        indexCardsBtn.setBounds(188, 640, 94, 65);

        progressTrackerBtn.setBackground(new java.awt.Color(217, 30, 24));
        progressTrackerBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        progressTrackerBtn.setForeground(new java.awt.Color(255, 255, 255));
        progressTrackerBtn.setText("<html>Progress<br> Tracker</html>");
        progressTrackerBtn.setContentAreaFilled(false);
        progressTrackerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        progressTrackerBtn.setOpaque(true);
        progressTrackerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progressTrackerBtnActionPerformed(evt);
            }
        });
        add(progressTrackerBtn);
        progressTrackerBtn.setBounds(281, 640, 94, 65);

        headerPnl.setBackground(new java.awt.Color(52, 73, 94));
        headerPnl.setForeground(new java.awt.Color(127, 140, 141));
        headerPnl.setToolTipText("");
        headerPnl.setLayout(null);

        headerTitleLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        headerTitleLbl.setForeground(new java.awt.Color(127, 140, 141));
        headerTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerPnl.add(headerTitleLbl);
        headerTitleLbl.setBounds(10, 35, 360, 28);

        currentDayLbl.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        currentDayLbl.setForeground(new java.awt.Color(127, 140, 141));
        currentDayLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        headerPnl.add(currentDayLbl);
        currentDayLbl.setBounds(15, 5, 60, 15);

        currentTimeLbl.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        currentTimeLbl.setForeground(new java.awt.Color(127, 140, 141));
        currentTimeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerPnl.add(currentTimeLbl);
        currentTimeLbl.setBounds(95, 5, 185, 15);

        currentDateLbl.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        currentDateLbl.setForeground(new java.awt.Color(127, 140, 141));
        currentDateLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerPnl.add(currentDateLbl);
        currentDateLbl.setBounds(280, 5, 90, 15);

        add(headerPnl);
        headerPnl.setBounds(0, 0, 380, 70);
    }// </editor-fold>//GEN-END:initComponents
    
    private void defaultNavColour(){
        timetableBtn.setBackground(new java.awt.Color(38, 166, 91));
        quizBtn.setBackground(new java.awt.Color(230, 126, 34));
        indexCardsBtn.setBackground(new java.awt.Color(191, 85, 236));
        progressTrackerBtn.setBackground(new java.awt.Color(217, 30, 24));
    }
    
    private void setTime(){
        Date myDate = new Date();
        SimpleDateFormat curDay = new SimpleDateFormat("E");
        SimpleDateFormat curTime = new SimpleDateFormat("HH:mm:ss");
        SimpleDateFormat curDate = new SimpleDateFormat("dd/MM/yyyy");
        currentDayLbl.setText(curDay.format(myDate));
        currentTimeLbl.setText(curTime.format(myDate));
        currentDateLbl.setText(curDate.format(myDate));
    }
    
    
    
    private void timetableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timetableBtnActionPerformed
        // TODO add your handling code here:
        headerTitleLbl.setText("Timetable");
        defaultNavColour();
        timetableBtn.setBackground(new java.awt.Color(135, 211, 124));
        LayoutManager layout = cardsContainer.getLayout();
        if(layout instanceof CardLayout){
            CardLayout cl = (CardLayout)layout;
            cl.show(cardsContainer, "TIMETABLE");
        }
    }//GEN-LAST:event_timetableBtnActionPerformed

    private void progressTrackerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progressTrackerBtnActionPerformed
        // TODO add your handling code here:
        headerTitleLbl.setText("Progress Tracker");
        defaultNavColour();
        progressTrackerBtn.setBackground(new java.awt.Color(242, 38, 19));
        LayoutManager layout = cardsContainer.getLayout();
        if(layout instanceof CardLayout){
            CardLayout cl = (CardLayout)layout;
            cl.show(cardsContainer, "PROGRESS");
        }
    }//GEN-LAST:event_progressTrackerBtnActionPerformed

    private void quizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizBtnActionPerformed
        // TODO add your handling code here:
        headerTitleLbl.setText("Quiz");
        defaultNavColour();
        quizBtn.setBackground(new java.awt.Color(245, 171, 53));
        LayoutManager layout = cardsContainer.getLayout();
        if(layout instanceof CardLayout){
            CardLayout cl = (CardLayout)layout;
            cl.show(cardsContainer, "QUIZ");
        }
    }//GEN-LAST:event_quizBtnActionPerformed

    private void indexCardsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexCardsBtnActionPerformed
        // TODO add your handling code here:
        headerTitleLbl.setText("Index Cards");
        defaultNavColour();
        indexCardsBtn.setBackground(new java.awt.Color(174, 168, 211));
        LayoutManager layout = cardsContainer.getLayout();
        if(layout instanceof CardLayout){
            CardLayout cl = (CardLayout)layout;
            cl.show(cardsContainer, "INDEX CARDS");
        }
    }//GEN-LAST:event_indexCardsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPnl;
    private javax.swing.JLabel currentDateLbl;
    private javax.swing.JLabel currentDayLbl;
    private javax.swing.JLabel currentTimeLbl;
    private javax.swing.JPanel headerPnl;
    private javax.swing.JLabel headerTitleLbl;
    private javax.swing.JButton indexCardsBtn;
    private javax.swing.JButton progressTrackerBtn;
    private javax.swing.JButton quizBtn;
    private javax.swing.JButton timetableBtn;
    // End of variables declaration//GEN-END:variables
}
