/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.awt.FlowLayout;
import javax.swing.JPanel;

/**
 *
 * @author x14729249
 */
public class MainJFrameApp extends javax.swing.JFrame {
    JPanel cardsContainer;
    
    /**
     * Creates new form MainJFrameApp
     */
    public MainJFrameApp() {
        initComponents();
        
        Login myLogin = new Login();
        MainScreenPanel myMainScreen = new MainScreenPanel();
        
        cardsContainer = new JPanel(new CardLayout());
        
        cardsContainer.add(myLogin, "LOGIN");
        cardsContainer.add(myMainScreen, "MAIN");
        
        contentPnl.setLayout(new FlowLayout(0, 0, 0));
        contentPnl.add(cardsContainer);
        CardLayout cl = (CardLayout)(cardsContainer.getLayout());
        cl.show(cardsContainer, "LOGIN");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPnl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(396, 750));
        setMinimumSize(new java.awt.Dimension(396, 750));
        setPreferredSize(new java.awt.Dimension(396, 750));
        getContentPane().setLayout(null);

        contentPnl.setMaximumSize(new java.awt.Dimension(377, 708));
        contentPnl.setMinimumSize(new java.awt.Dimension(377, 708));
        contentPnl.setPreferredSize(new java.awt.Dimension(377, 708));
        getContentPane().add(contentPnl);
        contentPnl.setBounds(0, 0, 377, 708);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPnl;
    // End of variables declaration//GEN-END:variables
}