/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.awt.LayoutManager;

/**
 *
 * @author x14729249
 */
public class ProgressGUI extends javax.swing.JPanel {

    /**
     * Creates new form ProgressGUI
     */
    public ProgressGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProgTrackMain = new javax.swing.JPanel();
        mathsBtn = new javax.swing.JButton();
        mathsIconLbl = new javax.swing.JLabel();
        dcgBtn = new javax.swing.JButton();
        dcgIconLbl = new javax.swing.JLabel();
        biologyBtn = new javax.swing.JButton();
        biologyIconLbl = new javax.swing.JLabel();
        physicsBtn = new javax.swing.JButton();
        physicsIconLbl = new javax.swing.JLabel();
        averageBtn = new javax.swing.JButton();
        averageIconLbl = new javax.swing.JLabel();

        ProgTrackMain.setBackground(new java.awt.Color(242, 38, 19));
        ProgTrackMain.setMaximumSize(new java.awt.Dimension(336, 532));
        ProgTrackMain.setMinimumSize(new java.awt.Dimension(336, 532));
        ProgTrackMain.setPreferredSize(new java.awt.Dimension(336, 532));
        ProgTrackMain.setLayout(null);

        mathsBtn.setBorderPainted(false);
        mathsBtn.setContentAreaFilled(false);
        mathsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mathsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathsBtnActionPerformed(evt);
            }
        });
        ProgTrackMain.add(mathsBtn);
        mathsBtn.setBounds(70, 110, 200, 40);

        mathsIconLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mathsBtn.png"))); // NOI18N
        ProgTrackMain.add(mathsIconLbl);
        mathsIconLbl.setBounds(70, 110, 200, 40);

        dcgBtn.setContentAreaFilled(false);
        dcgBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dcgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcgBtnActionPerformed(evt);
            }
        });
        ProgTrackMain.add(dcgBtn);
        dcgBtn.setBounds(70, 175, 200, 40);

        dcgIconLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dcgBtn.png"))); // NOI18N
        ProgTrackMain.add(dcgIconLbl);
        dcgIconLbl.setBounds(70, 175, 200, 40);

        biologyBtn.setContentAreaFilled(false);
        biologyBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        biologyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biologyBtnActionPerformed(evt);
            }
        });
        ProgTrackMain.add(biologyBtn);
        biologyBtn.setBounds(70, 240, 200, 40);

        biologyIconLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/biologyBtn.png"))); // NOI18N
        ProgTrackMain.add(biologyIconLbl);
        biologyIconLbl.setBounds(70, 240, 200, 40);

        physicsBtn.setContentAreaFilled(false);
        physicsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        physicsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physicsBtnActionPerformed(evt);
            }
        });
        ProgTrackMain.add(physicsBtn);
        physicsBtn.setBounds(70, 305, 200, 40);

        physicsIconLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/physicsBtn.png"))); // NOI18N
        ProgTrackMain.add(physicsIconLbl);
        physicsIconLbl.setBounds(70, 305, 200, 40);

        averageBtn.setContentAreaFilled(false);
        averageBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        averageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                averageBtnActionPerformed(evt);
            }
        });
        ProgTrackMain.add(averageBtn);
        averageBtn.setBounds(70, 370, 200, 40);

        averageIconLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/averageBtn.png"))); // NOI18N
        ProgTrackMain.add(averageIconLbl);
        averageIconLbl.setBounds(70, 370, 200, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProgTrackMain, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProgTrackMain, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mathsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathsBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if(layout instanceof CardLayout){
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "SUBJECT");
        }
    }//GEN-LAST:event_mathsBtnActionPerformed

    private void averageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_averageBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if(layout instanceof CardLayout){
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "AVERAGE");
        }
    }//GEN-LAST:event_averageBtnActionPerformed

    private void dcgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcgBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if(layout instanceof CardLayout){
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "SUBJECT");
        }
    }//GEN-LAST:event_dcgBtnActionPerformed

    private void biologyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biologyBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if(layout instanceof CardLayout){
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "SUBJECT");
        }
    }//GEN-LAST:event_biologyBtnActionPerformed

    private void physicsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physicsBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if(layout instanceof CardLayout){
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "SUBJECT");
        }
    }//GEN-LAST:event_physicsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ProgTrackMain;
    private javax.swing.JButton averageBtn;
    private javax.swing.JLabel averageIconLbl;
    private javax.swing.JButton biologyBtn;
    private javax.swing.JLabel biologyIconLbl;
    private javax.swing.JButton dcgBtn;
    private javax.swing.JLabel dcgIconLbl;
    private javax.swing.JButton mathsBtn;
    private javax.swing.JLabel mathsIconLbl;
    private javax.swing.JButton physicsBtn;
    private javax.swing.JLabel physicsIconLbl;
    // End of variables declaration//GEN-END:variables
}
