/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import java.awt.CardLayout;
import java.awt.Desktop;
import java.awt.LayoutManager;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.Random;

/*
 * QuizMainGUI.java
 * @author Danny O'Sullivan
 * Student No. x14110750
 */
public class QuizMainGUI extends javax.swing.JPanel {

    /**
     * Creates new form QuizGUI
     */
    public QuizMainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QuizMainPanel = new javax.swing.JPanel();
        SubOneBtn = new javax.swing.JButton();
        SubTwoBtn = new javax.swing.JButton();
        SubThreeBtn = new javax.swing.JButton();
        SubFourBtn = new javax.swing.JButton();
        PastPapersBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(336, 532));
        setLayout(null);

        QuizMainPanel.setBackground(new java.awt.Color(245, 171, 53));
        QuizMainPanel.setLayout(null);

        SubOneBtn.setBackground(new java.awt.Color(230, 126, 34));
        SubOneBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bio-btn.png"))); // NOI18N
        SubOneBtn.setContentAreaFilled(false);
        SubOneBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SubOneBtn.setMaximumSize(new java.awt.Dimension(145, 150));
        SubOneBtn.setMinimumSize(new java.awt.Dimension(145, 150));
        SubOneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubOneBtnActionPerformed(evt);
            }
        });
        QuizMainPanel.add(SubOneBtn);
        SubOneBtn.setBounds(180, 53, 145, 150);

        SubTwoBtn.setBackground(new java.awt.Color(230, 126, 34));
        SubTwoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/phy-btn.png"))); // NOI18N
        SubTwoBtn.setContentAreaFilled(false);
        SubTwoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SubTwoBtn.setMaximumSize(new java.awt.Dimension(130, 130));
        SubTwoBtn.setMinimumSize(new java.awt.Dimension(145, 150));
        SubTwoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubTwoBtnActionPerformed(evt);
            }
        });
        QuizMainPanel.add(SubTwoBtn);
        SubTwoBtn.setBounds(10, 53, 145, 150);

        SubThreeBtn.setBackground(new java.awt.Color(230, 126, 34));
        SubThreeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dcg-btn.png"))); // NOI18N
        SubThreeBtn.setContentAreaFilled(false);
        SubThreeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SubThreeBtn.setMaximumSize(new java.awt.Dimension(145, 150));
        SubThreeBtn.setMinimumSize(new java.awt.Dimension(145, 150));
        SubThreeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubThreeBtnActionPerformed(evt);
            }
        });
        QuizMainPanel.add(SubThreeBtn);
        SubThreeBtn.setBounds(180, 256, 145, 150);

        SubFourBtn.setBackground(new java.awt.Color(230, 126, 34));
        SubFourBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mat-btn.png"))); // NOI18N
        SubFourBtn.setContentAreaFilled(false);
        SubFourBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SubFourBtn.setMaximumSize(new java.awt.Dimension(145, 150));
        SubFourBtn.setMinimumSize(new java.awt.Dimension(145, 150));
        SubFourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubFourBtnActionPerformed(evt);
            }
        });
        QuizMainPanel.add(SubFourBtn);
        SubFourBtn.setBounds(10, 256, 145, 150);

        PastPapersBtn.setBackground(new java.awt.Color(230, 126, 34));
        PastPapersBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pp-btn.png"))); // NOI18N
        PastPapersBtn.setContentAreaFilled(false);
        PastPapersBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PastPapersBtn.setPreferredSize(new java.awt.Dimension(1245, 225));
        PastPapersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PastPapersBtnActionPerformed(evt);
            }
        });
        QuizMainPanel.add(PastPapersBtn);
        PastPapersBtn.setBounds(5, 435, 326, 65);

        add(QuizMainPanel);
        QuizMainPanel.setBounds(0, 0, 336, 532);
    }// </editor-fold>//GEN-END:initComponents

    private void SubOneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubOneBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if(layout instanceof CardLayout){
            CardLayout cl = (CardLayout)layout;    
            cl.show(getParent(), "IMAGE QUIZ");
        }
    }//GEN-LAST:event_SubOneBtnActionPerformed

    private void SubTwoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubTwoBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if(layout instanceof CardLayout){
            CardLayout cl = (CardLayout)layout;
            Random r = new Random();
            int rand = r.nextInt(3);
            if(rand == 0){
                cl.show(getParent(), "IMAGE QUIZ");
            }else if(rand == 1){
                cl.show(getParent(), "MULTI QUIZ");
            }else{
                cl.show(getParent(), "TEXT QUIZ");
            }
        }
    }//GEN-LAST:event_SubTwoBtnActionPerformed

    private void SubThreeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubThreeBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if(layout instanceof CardLayout){
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "TEXT QUIZ");
        }
    }//GEN-LAST:event_SubThreeBtnActionPerformed

    private void SubFourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubFourBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if(layout instanceof CardLayout){
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "MULTI QUIZ");
        }
    }//GEN-LAST:event_SubFourBtnActionPerformed

    private void PastPapersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PastPapersBtnActionPerformed
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://examinations.ie/index.php?l=en&mc=en&sc=ep&ty=e").toURI());
        }catch (IOException | URISyntaxException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_PastPapersBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PastPapersBtn;
    private javax.swing.JPanel QuizMainPanel;
    private javax.swing.JButton SubFourBtn;
    private javax.swing.JButton SubOneBtn;
    private javax.swing.JButton SubThreeBtn;
    private javax.swing.JButton SubTwoBtn;
    // End of variables declaration//GEN-END:variables
}
