/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Dan
 */
public class TaskInfo extends javax.swing.JPanel {

    /**
     * Creates new form TaskInfo
     */
    public TaskInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TimetableContent = new javax.swing.JPanel();
        TaskTypeTitle = new javax.swing.JLabel();
        TaskTypeRB1 = new javax.swing.JRadioButton();
        TaskTypeRB2 = new javax.swing.JRadioButton();
        TaskTypeRB3 = new javax.swing.JRadioButton();
        TaskDetailsTitle = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setLayout(null);

        TimetableContent.setBackground(new java.awt.Color(135, 211, 124));
        TimetableContent.setLayout(null);

        TaskTypeTitle.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        TaskTypeTitle.setForeground(new java.awt.Color(255, 255, 255));
        TaskTypeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TaskTypeTitle.setText("Task Type");
        TimetableContent.add(TaskTypeTitle);
        TaskTypeTitle.setBounds(0, 10, 335, 53);

        TaskTypeRB1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TaskTypeRB1.setForeground(new java.awt.Color(255, 255, 255));
        TaskTypeRB1.setText("Study");
        TaskTypeRB1.setContentAreaFilled(false);
        TimetableContent.add(TaskTypeRB1);
        TaskTypeRB1.setBounds(40, 80, 150, 31);

        TaskTypeRB2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TaskTypeRB2.setForeground(new java.awt.Color(255, 255, 255));
        TaskTypeRB2.setText("Homework");
        TaskTypeRB2.setContentAreaFilled(false);
        TimetableContent.add(TaskTypeRB2);
        TaskTypeRB2.setBounds(40, 130, 150, 31);

        TaskTypeRB3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        TaskTypeRB3.setForeground(new java.awt.Color(255, 255, 255));
        TaskTypeRB3.setText("Quiz");
        TaskTypeRB3.setContentAreaFilled(false);
        TimetableContent.add(TaskTypeRB3);
        TaskTypeRB3.setBounds(40, 180, 150, 31);

        TaskDetailsTitle.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        TaskDetailsTitle.setForeground(new java.awt.Color(255, 255, 255));
        TaskDetailsTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TaskDetailsTitle.setText("Task Details");
        TimetableContent.add(TaskDetailsTitle);
        TaskDetailsTitle.setBounds(0, 250, 335, 53);

        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Sample task details");
        jTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TimetableContent.add(jTextField1);
        jTextField1.setBounds(40, 320, 256, 172);

        add(TimetableContent);
        TimetableContent.setBounds(0, 0, 336, 532);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TaskDetailsTitle;
    private javax.swing.JRadioButton TaskTypeRB1;
    private javax.swing.JRadioButton TaskTypeRB2;
    private javax.swing.JRadioButton TaskTypeRB3;
    private javax.swing.JLabel TaskTypeTitle;
    private javax.swing.JPanel TimetableContent;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
