/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Dan
 */
public class TestYourself extends javax.swing.JPanel {

    /**
     * Creates new form TestYourself
     */
    public TestYourself() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testYourselfPnl = new javax.swing.JPanel();
        indexCardPlaceholder = new javax.swing.JLabel();
        nextBtn = new javax.swing.JButton();
        answerA = new javax.swing.JRadioButton();
        answerB = new javax.swing.JRadioButton();
        answerC = new javax.swing.JRadioButton();
        answerD = new javax.swing.JRadioButton();

        setMinimumSize(new java.awt.Dimension(336, 532));
        setLayout(null);

        testYourselfPnl.setBackground(new java.awt.Color(174, 168, 211));
        testYourselfPnl.setMinimumSize(new java.awt.Dimension(336, 532));
        testYourselfPnl.setLayout(null);

        indexCardPlaceholder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/indexCardExample.png"))); // NOI18N
        indexCardPlaceholder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        testYourselfPnl.add(indexCardPlaceholder);
        indexCardPlaceholder.setBounds(23, 20, 290, 290);

        nextBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nextButton.png"))); // NOI18N
        nextBtn.setContentAreaFilled(false);
        testYourselfPnl.add(nextBtn);
        nextBtn.setBounds(58, 440, 220, 50);

        answerA.setBackground(new java.awt.Color(74, 136, 220));
        answerA.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        answerA.setForeground(new java.awt.Color(255, 255, 255));
        answerA.setText("A");
        answerA.setContentAreaFilled(false);
        answerA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        answerA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerAActionPerformed(evt);
            }
        });
        testYourselfPnl.add(answerA);
        answerA.setBounds(80, 340, 40, 31);

        answerB.setBackground(new java.awt.Color(75, 137, 220));
        answerB.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        answerB.setForeground(new java.awt.Color(255, 255, 255));
        answerB.setText("B");
        answerB.setContentAreaFilled(false);
        answerB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        answerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerBActionPerformed(evt);
            }
        });
        testYourselfPnl.add(answerB);
        answerB.setBounds(80, 380, 40, 31);

        answerC.setBackground(new java.awt.Color(75, 137, 220));
        answerC.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        answerC.setForeground(new java.awt.Color(255, 255, 255));
        answerC.setText("C");
        answerC.setContentAreaFilled(false);
        answerC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        answerC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerCActionPerformed(evt);
            }
        });
        testYourselfPnl.add(answerC);
        answerC.setBounds(216, 340, 40, 31);

        answerD.setBackground(new java.awt.Color(75, 137, 220));
        answerD.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        answerD.setForeground(new java.awt.Color(255, 255, 255));
        answerD.setText("D");
        answerD.setContentAreaFilled(false);
        answerD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        answerD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerDActionPerformed(evt);
            }
        });
        testYourselfPnl.add(answerD);
        answerD.setBounds(216, 380, 40, 31);

        add(testYourselfPnl);
        testYourselfPnl.setBounds(0, 0, 336, 532);
    }// </editor-fold>//GEN-END:initComponents

    private void answerAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerAActionPerformed

    private void answerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerBActionPerformed

    private void answerCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerCActionPerformed

    private void answerDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton answerA;
    private javax.swing.JRadioButton answerB;
    private javax.swing.JRadioButton answerC;
    private javax.swing.JRadioButton answerD;
    private javax.swing.JLabel indexCardPlaceholder;
    private javax.swing.JButton nextBtn;
    private javax.swing.JPanel testYourselfPnl;
    // End of variables declaration//GEN-END:variables
}
