/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

/**
 *
 * @author x14110750
 */
public class TextQuizGUI extends javax.swing.JPanel {

    /**
     * Creates new form TextQuizGUI
     */
    public TextQuizGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextQuizPanel = new javax.swing.JPanel();
        AnswerTextQuizLbl = new javax.swing.JLabel();
        AnswerTextQuiz = new javax.swing.JTextField();
        NextBtnTextQuiz = new javax.swing.JButton();
        QuestionNoLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(336, 532));
        setMinimumSize(new java.awt.Dimension(336, 532));
        setPreferredSize(new java.awt.Dimension(336, 532));
        setLayout(null);

        TextQuizPanel.setBackground(new java.awt.Color(245, 171, 53));
        TextQuizPanel.setMinimumSize(new java.awt.Dimension(336, 532));

        AnswerTextQuizLbl.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        AnswerTextQuizLbl.setText("Answer:");

        NextBtnTextQuiz.setText("Next");

        QuestionNoLbl.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        QuestionNoLbl.setText("Question 1:");

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>What is the melting point of Iron in Degrees Celsius? </html>");

        javax.swing.GroupLayout TextQuizPanelLayout = new javax.swing.GroupLayout(TextQuizPanel);
        TextQuizPanel.setLayout(TextQuizPanelLayout);
        TextQuizPanelLayout.setHorizontalGroup(
            TextQuizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextQuizPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(TextQuizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NextBtnTextQuiz)
                    .addGroup(TextQuizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(AnswerTextQuizLbl)
                        .addComponent(QuestionNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AnswerTextQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        TextQuizPanelLayout.setVerticalGroup(
            TextQuizPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TextQuizPanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(QuestionNoLbl)
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(AnswerTextQuizLbl)
                .addGap(18, 18, 18)
                .addComponent(AnswerTextQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(NextBtnTextQuiz)
                .addGap(126, 126, 126))
        );

        add(TextQuizPanel);
        TextQuizPanel.setBounds(0, 0, 340, 530);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnswerTextQuiz;
    private javax.swing.JLabel AnswerTextQuizLbl;
    private javax.swing.JButton NextBtnTextQuiz;
    private javax.swing.JLabel QuestionNoLbl;
    private javax.swing.JPanel TextQuizPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
