/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.awt.FlowLayout;
import java.awt.LayoutManager;
import javax.swing.JPanel;

/**
 *
 * @author Dan
 */
public class Timetable extends javax.swing.JPanel {
    
    /**
     * Creates new form Timetable
     */
    public Timetable() {
        initComponents();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TimetableContent = new javax.swing.JPanel();
        TimetableNavBtns = new javax.swing.JPanel();
        PrevDayBtn = new javax.swing.JButton();
        NextDayBtn = new javax.swing.JButton();
        SelectedDayLbl = new javax.swing.JLabel();
        TimeSlotBtns = new javax.swing.JPanel();
        timeSlotBtn1 = new javax.swing.JButton();
        timeSlotBtn2 = new javax.swing.JButton();
        timeSlotBtn4 = new javax.swing.JButton();
        timeSlotBtn5 = new javax.swing.JButton();
        timeSlotBtn6 = new javax.swing.JButton();
        timeSlotBtn7 = new javax.swing.JButton();
        TimeSlotLbls = new javax.swing.JPanel();
        timeSlot1Type = new javax.swing.JLabel();
        timeSlot2Type = new javax.swing.JLabel();
        timeSlot3 = new javax.swing.JLabel();
        timeSlot4Type = new javax.swing.JLabel();
        timeSlot5Type = new javax.swing.JLabel();
        timeSlot6Type = new javax.swing.JLabel();
        timeSlot7Type = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 0, 102));
        setFocusCycleRoot(true);
        setMinimumSize(new java.awt.Dimension(336, 532));
        setOpaque(false);
        setLayout(null);

        TimetableContent.setBackground(new java.awt.Color(135, 211, 124));
        TimetableContent.setLayout(null);

        TimetableNavBtns.setBackground(new java.awt.Color(255, 255, 255));
        TimetableNavBtns.setOpaque(false);
        TimetableNavBtns.setLayout(null);

        PrevDayBtn.setBackground(new java.awt.Color(255, 255, 255));
        PrevDayBtn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        PrevDayBtn.setForeground(new java.awt.Color(255, 255, 255));
        PrevDayBtn.setText("Prev Day");
        PrevDayBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        PrevDayBtn.setContentAreaFilled(false);
        PrevDayBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TimetableNavBtns.add(PrevDayBtn);
        PrevDayBtn.setBounds(0, 0, 112, 108);

        NextDayBtn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        NextDayBtn.setForeground(new java.awt.Color(255, 255, 255));
        NextDayBtn.setText("Next Day");
        NextDayBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        NextDayBtn.setContentAreaFilled(false);
        NextDayBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TimetableNavBtns.add(NextDayBtn);
        NextDayBtn.setBounds(224, 0, 112, 108);

        SelectedDayLbl.setBackground(new java.awt.Color(255, 255, 255));
        SelectedDayLbl.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        SelectedDayLbl.setForeground(new java.awt.Color(255, 255, 255));
        SelectedDayLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SelectedDayLbl.setText("Selected Day");
        SelectedDayLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        TimetableNavBtns.add(SelectedDayLbl);
        SelectedDayLbl.setBounds(112, 0, 112, 108);

        TimetableContent.add(TimetableNavBtns);
        TimetableNavBtns.setBounds(0, 0, 336, 108);

        TimeSlotBtns.setOpaque(false);
        TimeSlotBtns.setLayout(null);

        timeSlotBtn1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        timeSlotBtn1.setForeground(new java.awt.Color(255, 255, 255));
        timeSlotBtn1.setText("6am-7am");
        timeSlotBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        timeSlotBtn1.setContentAreaFilled(false);
        timeSlotBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timeSlotBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeSlotBtn1ActionPerformed(evt);
            }
        });
        TimeSlotBtns.add(timeSlotBtn1);
        timeSlotBtn1.setBounds(0, 0, 336, 53);

        timeSlotBtn2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        timeSlotBtn2.setForeground(new java.awt.Color(255, 255, 255));
        timeSlotBtn2.setText("7am-8am");
        timeSlotBtn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        timeSlotBtn2.setContentAreaFilled(false);
        timeSlotBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timeSlotBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeSlotBtn2ActionPerformed(evt);
            }
        });
        TimeSlotBtns.add(timeSlotBtn2);
        timeSlotBtn2.setBounds(0, 53, 336, 53);

        timeSlotBtn4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        timeSlotBtn4.setForeground(new java.awt.Color(255, 255, 255));
        timeSlotBtn4.setText("6pm-7pm");
        timeSlotBtn4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        timeSlotBtn4.setContentAreaFilled(false);
        timeSlotBtn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timeSlotBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeSlotBtn4ActionPerformed(evt);
            }
        });
        TimeSlotBtns.add(timeSlotBtn4);
        timeSlotBtn4.setBounds(0, 212, 336, 53);

        timeSlotBtn5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        timeSlotBtn5.setForeground(new java.awt.Color(255, 255, 255));
        timeSlotBtn5.setText("7pm-8pm");
        timeSlotBtn5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        timeSlotBtn5.setContentAreaFilled(false);
        timeSlotBtn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timeSlotBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeSlotBtn5ActionPerformed(evt);
            }
        });
        TimeSlotBtns.add(timeSlotBtn5);
        timeSlotBtn5.setBounds(0, 265, 336, 53);

        timeSlotBtn6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        timeSlotBtn6.setForeground(new java.awt.Color(255, 255, 255));
        timeSlotBtn6.setText("8pm-9pm");
        timeSlotBtn6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        timeSlotBtn6.setContentAreaFilled(false);
        timeSlotBtn6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timeSlotBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeSlotBtn6ActionPerformed(evt);
            }
        });
        TimeSlotBtns.add(timeSlotBtn6);
        timeSlotBtn6.setBounds(0, 318, 336, 53);

        timeSlotBtn7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        timeSlotBtn7.setForeground(new java.awt.Color(255, 255, 255));
        timeSlotBtn7.setText("9pm-10pm");
        timeSlotBtn7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        timeSlotBtn7.setContentAreaFilled(false);
        timeSlotBtn7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timeSlotBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeSlotBtn7ActionPerformed(evt);
            }
        });
        TimeSlotBtns.add(timeSlotBtn7);
        timeSlotBtn7.setBounds(0, 371, 336, 53);

        TimetableContent.add(TimeSlotBtns);
        TimeSlotBtns.setBounds(0, 108, 336, 424);

        TimeSlotLbls.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 160, 133)));
        TimeSlotLbls.setOpaque(false);
        TimeSlotLbls.setLayout(null);

        timeSlot1Type.setBackground(new java.awt.Color(255, 204, 51));
        timeSlot1Type.setFont(new java.awt.Font("Narkisim", 2, 14)); // NOI18N
        timeSlot1Type.setForeground(new java.awt.Color(255, 255, 255));
        timeSlot1Type.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        timeSlot1Type.setText("  Quiz");
        timeSlot1Type.setAlignmentX(1.0F);
        timeSlot1Type.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        timeSlot1Type.setOpaque(true);
        TimeSlotLbls.add(timeSlot1Type);
        timeSlot1Type.setBounds(0, 0, 336, 53);

        timeSlot2Type.setFont(new java.awt.Font("Narkisim", 2, 14)); // NOI18N
        timeSlot2Type.setForeground(new java.awt.Color(255, 255, 255));
        timeSlot2Type.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        timeSlot2Type.setText("  [Task Type]");
        timeSlot2Type.setAlignmentX(1.0F);
        timeSlot2Type.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TimeSlotLbls.add(timeSlot2Type);
        timeSlot2Type.setBounds(0, 53, 336, 53);

        timeSlot3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        timeSlot3.setForeground(new java.awt.Color(255, 255, 255));
        timeSlot3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeSlot3.setText("SCHOOL TIME");
        timeSlot3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TimeSlotLbls.add(timeSlot3);
        timeSlot3.setBounds(0, 106, 336, 106);

        timeSlot4Type.setBackground(new java.awt.Color(0, 102, 255));
        timeSlot4Type.setFont(new java.awt.Font("Narkisim", 2, 14)); // NOI18N
        timeSlot4Type.setForeground(new java.awt.Color(255, 255, 255));
        timeSlot4Type.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        timeSlot4Type.setText("  Homework");
        timeSlot4Type.setAlignmentX(1.0F);
        timeSlot4Type.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        timeSlot4Type.setOpaque(true);
        TimeSlotLbls.add(timeSlot4Type);
        timeSlot4Type.setBounds(0, 212, 336, 53);

        timeSlot5Type.setFont(new java.awt.Font("Narkisim", 2, 14)); // NOI18N
        timeSlot5Type.setForeground(new java.awt.Color(255, 255, 255));
        timeSlot5Type.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        timeSlot5Type.setText("  [Task Type]");
        timeSlot5Type.setAlignmentX(1.0F);
        timeSlot5Type.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TimeSlotLbls.add(timeSlot5Type);
        timeSlot5Type.setBounds(0, 265, 336, 53);

        timeSlot6Type.setBackground(new java.awt.Color(204, 0, 102));
        timeSlot6Type.setFont(new java.awt.Font("Narkisim", 2, 14)); // NOI18N
        timeSlot6Type.setForeground(new java.awt.Color(255, 255, 255));
        timeSlot6Type.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        timeSlot6Type.setText("  Study");
        timeSlot6Type.setAlignmentX(1.0F);
        timeSlot6Type.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        timeSlot6Type.setOpaque(true);
        TimeSlotLbls.add(timeSlot6Type);
        timeSlot6Type.setBounds(0, 318, 336, 53);

        timeSlot7Type.setFont(new java.awt.Font("Narkisim", 2, 14)); // NOI18N
        timeSlot7Type.setForeground(new java.awt.Color(255, 255, 255));
        timeSlot7Type.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        timeSlot7Type.setText("  [Task Type]");
        timeSlot7Type.setAlignmentX(1.0F);
        timeSlot7Type.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TimeSlotLbls.add(timeSlot7Type);
        timeSlot7Type.setBounds(0, 371, 336, 53);

        TimetableContent.add(TimeSlotLbls);
        TimeSlotLbls.setBounds(0, 108, 336, 424);

        add(TimetableContent);
        TimetableContent.setBounds(0, 0, 336, 532);
    }// </editor-fold>//GEN-END:initComponents
    
    private void timeSlotBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeSlotBtn1ActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "TASK INFO");
        }
    }//GEN-LAST:event_timeSlotBtn1ActionPerformed

    private void timeSlotBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeSlotBtn2ActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "TASK INFO");
        }
    }//GEN-LAST:event_timeSlotBtn2ActionPerformed

    private void timeSlotBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeSlotBtn4ActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "TASK INFO");
        }
    }//GEN-LAST:event_timeSlotBtn4ActionPerformed

    private void timeSlotBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeSlotBtn5ActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "TASK INFO");
        }
    }//GEN-LAST:event_timeSlotBtn5ActionPerformed

    private void timeSlotBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeSlotBtn6ActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "TASK INFO");
        }
    }//GEN-LAST:event_timeSlotBtn6ActionPerformed

    private void timeSlotBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeSlotBtn7ActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "TASK INFO");
        }
    }//GEN-LAST:event_timeSlotBtn7ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NextDayBtn;
    private javax.swing.JButton PrevDayBtn;
    private javax.swing.JLabel SelectedDayLbl;
    private javax.swing.JPanel TimeSlotBtns;
    private javax.swing.JPanel TimeSlotLbls;
    private javax.swing.JPanel TimetableContent;
    private javax.swing.JPanel TimetableNavBtns;
    private javax.swing.JLabel timeSlot1Type;
    private javax.swing.JLabel timeSlot2Type;
    private javax.swing.JLabel timeSlot3;
    private javax.swing.JLabel timeSlot4Type;
    private javax.swing.JLabel timeSlot5Type;
    private javax.swing.JLabel timeSlot6Type;
    private javax.swing.JLabel timeSlot7Type;
    private javax.swing.JButton timeSlotBtn1;
    private javax.swing.JButton timeSlotBtn2;
    private javax.swing.JButton timeSlotBtn4;
    private javax.swing.JButton timeSlotBtn5;
    private javax.swing.JButton timeSlotBtn6;
    private javax.swing.JButton timeSlotBtn7;
    // End of variables declaration//GEN-END:variables
}
